version: "3.7"
services:
  web:
    user: root
    image: antaema/docker_images:nginx
    volumes:
    - ./server.conf:/etc/nginx/conf.d/server.conf
    - ./gulpfile.js:/home/dev/gulpfile.js
    - ./package.json:/home/dev/package.json
    - ../src:/home/dev/src:cached
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=gintama.com
    - NGINX_PORT=80
    command:  /bin/bash -c "chmod 777 -R /etc/nginx/conf.d/ && envsubst < /etc/nginx/conf.d/server.conf> /etc/nginx/conf.d/default.conf &&  exec nginx -g 'daemon off;'"
